# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'VKClient' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Alamofire', '~> 5.2'

  pod 'RealmSwift'

  pod 'Firebase/Analytics'
  pod 'Firebase/Database'
  pod 'Firebase/Firestore'
  pod 'Firebase/Auth'
  pod 'Firebase/Crashlytics'

  # Pods for VKClient

end
