# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'VKClient' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Alamofire', '~> 4.0'

  pod 'RealmSwift'

  pod 'PromiseKit/Alamofire', '~> 6.0'

  # Pods for VKClient

end
